stages:
  - lint
  - build

markdown_lint:
  image: node:11.12.0-alpine
  stage: lint
  before_script:
    - npm install -g textlint textlint-rule-prh textlint-rule-aws-spellcheck textlint-rule-preset-ja-technical-writing textlint-rule-spellcheck-tech-word
  script:
    - find docs -name \*.md | xargs -I{} sh -c "textlint {}"

pdf_build:
  image: vvakame/review:4.0
  stage: build
  before_script:
    - apt-get update -y
    - apt-get -y install build-essential ruby-dev
    - gem install md2review
  script:
    # MDからRe:VIEWファイルを作成
    - for a in `find docs -name \*.md | sort`; do md2review "${a}" > `basename "${a}" .md`.re; done;
    # catalog.ymlの作成
    # イメージの確認が目的なので章の順番とかは無視してとりあえずPDFにしている。
    # きちんとPDFにする場合はcatalog.ymlを手でメンテするかmdファイルの命名ルールを厳格化して自動生成しやすい構成にする。
    - echo -e "PREDEF:\n" > catalog.yml;echo -e "CHAPS:" >> catalog.yml;for a in `find . -name \*.re | sort`; do echo "  - `basename "${a}" .md`" >>  catalog.yml; done;echo -e "\nPREDEF:\n" >> catalog.yml;echo -e "POSTDEF:\n" >> catalog.yml;
    # PDF化
    - review-pdfmaker config.yml
  artifacts:
    untracked: true
  only:
    - master
    - release-candidate
    - /^feature\/.*$/
